{"name": "test_dome", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <Testcase.test_login.TestLogin object at 0x7fefc83bbac0>\n\n    @pytest.mark.dome()\n    def test_dome(self):\n        print(\"我是dome\")\n>       assert False\nE       assert False\n\nTestcase/test_login.py:52: AssertionError"}, "attachments": [{"name": "log", "source": "a25c040f-1fda-474d-a4ca-490507a432ec-attachment.txt", "type": "text/plain"}], "start": 1658667898816, "stop": 1658667898816, "uuid": "a1af4991-1a36-4a3b-82a0-b4ba5c82e0b5", "historyId": "91096dcc6dd541c919b1169920a8bf16", "testCaseId": "0879cece16e3b0cc90088b73f853737a", "fullName": "Testcase.test_login.TestLogin#test_dome", "labels": [{"name": "tag", "value": "dome"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_web')"}, {"name": "parentSuite", "value": "Testcase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wepiedeMBP-3.lan"}, {"name": "thread", "value": "4923-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase.test_login"}]}